language: objective-c
osx_image: xcode8.3
cache:
  - directories:
    - Carthage
before_install: true
install:
  - rvm get stable || true
  - brew update || true
  - brew install carthage || true
  - brew outdated carthage || brew upgrade carthage
before_script:
  - chmod +x ./script/build
xcode_project: CoordinatorKit.xcodeproj
matrix:
  include:
    - script:
      - carthage bootstrap --no-use-binaries --platform iOS
      - script/build
      xcode_scheme: CoordinatorKit-iOS
      env:
        - XCODE_SDK=iphonesimulator
        - XCODE_ACTION="build-for-testing test-without-building"
        - XCODE_DESTINATION="platform=iOS Simulator,name=iPhone 6s"
    - script:
      - pod repo update
      - travis_wait 30 pod lib lint CoordinatorKit.podspec
      env:
        - JOB=PODSPEC
